apiVersion: v1
kind:  ConfigMap
metadata:
  name:  employee-config-dev
  namespace:  sabbavarapusatishkum-dev
  labels:
    app: employee-app
    environment: dev
data:
  APP_ENV: "development"
  LOG_LEVEL: "DEBUG"
  APP_VERSION: "1.0.0"
  APP_MESSAGE: "Welcome To Dev Environment"
  MAX_CONNECTIONS: "10"
