apiVersion: v1
kind: Secret
metadata:
  name: employee-secret-test
  namespace: sabbavarapusatishkum-dev
  labels:
    app: employee-app
    environment: test
type: Opaque
stringData:
  DB_PASSWORD: "testPassword123"
  API_KEY: "test-api-key-xyz"
  JWT_SECRET: "test-jwt-secret-abc"
