apiVersion: v1
kind: Secret
metadata:
  name: employee-secret-prod
  namespace: sabbavarapusatishkum-dev
  labels:
    app: employee-app
    environment: prod
type: Opaque
stringData:
  DB_PASSWORD: "prodPassword123"
  API_KEY: "prod-api-key-xyz"
  JWT_SECRET: "prod-jwt-secret-abc"
