apiVersion: v1
kind:  Secret
metadata:
  name:  employee-secret-dev
  namespace:  sabbavarapusatishkum-dev
  labels:
    app: employee-app
    environment: dev
type: Opaque
StringData:
  DB_PASSWORD: "devPassword123"
  API_KEY: "dev-api-key-xyz"
  JWT_SECRET: "dev-jwt-secret-abc"
