spring.application.name=employee-app
app.version=1.0.0
app.environment=${APP_ENV:development}
server.port=9090

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true

# THIS IS THE FIX - adds app name as label in metrics
management.metrics.tags.application=${spring.application.name}
