# PROD specific values
# PROD gets MORE resources!

environment: production
replicaCount: 2

config:
  APP_ENV: "production"
  LOG_LEVEL: "ERROR"
  APP_MESSAGE: "Welcome to PRODUCTION"
  MAX_CONNECTIONS: "100"

# PROD gets more resources!
resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"

# PROD scales higher!
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization: 70
