apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: employee-app-role
  namespace: sabbavarapusatishkum-dev
rules:

# What this role CAN DO:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
  # Can READ pods but NOT delete!

- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
  # Can READ services

- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update"]
  # Can READ and UPDATE deployments

- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
  # Can READ configmaps

- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]
  # CANNOT read secrets! Security! í´’
