apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    environment: {{ .Values.environment }}
data:
  APP_ENV: {{ .Values.config.APP_ENV | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  APP_VERSION: {{ .Values.config.APP_VERSION | quote }}
  APP_MESSAGE: {{ .Values.config.APP_MESSAGE | quote }}
  MAX_CONNECTIONS: {{ .Values.config.MAX_CONNECTIONS | quote }}
